UAlbertaCompEClub/compe-plus

.prettierrc, api/.eslintignore, api/.eslintrc.js, api/.prettierignore, api/jest.config.js, api/package.json, api/src/controllers/sample.ts, api/src/routes/middleware.test.ts, api/src/routes/middleware.ts, api/src/routes/sample.ts, api/src/server.ts, api/src/util/config.ts, api/src/util/logging.ts, api/tsconfig.json
- Add `typescript-eslint` for server linting (ensures no unused variables, etc.)
- Use single quotes for prettier
- Run format on `src/`
- Eslint will warn on formatting violations
- Server's eslint and client's eslint should be separated because they'll use different plugins (e.g. the front end stuff will use eslint-react)
=> Add typescript-eslint to server

.github/workflows/main.yml, api/README.md, api/package.json, api/src/controllers/sample.ts, api/src/routes/middleware.test.ts, api/src/routes/middleware.ts, api/src/util/logging.ts, www/README.md
- Setup continuous integration for `api`.
- Disallow lint warnings... Too strict? I kind of like the strictness to keep our codebase squeaky clean.
- Fix warnings and modify tests as needed
- Setup continuous integration for `www`.
- Cache `npm i` in actions
Tickets have been added
Closes #13
=> Setup continuous integration for api

api/.eslintrc.js, api/README.md, api/package-lock.json, api/package.json, api/src/controllers/sample.ts, api/src/routes/middleware.test.ts, api/src/routes/middleware.ts, api/src/routes/sample.ts, api/src/server.ts, api/src/util/logger.ts, api/src/util/pool.ts
Setup linting to sort imports for API. I'm tired of dealing with this myself.
- Add plugin to ESLint to sort imports
- Add script to run ESLint fixes
- Should we use same plugin in www?
=> Sort imports for API

www/package-lock.json
Fresh repo clone won't let you run `npm start` to serve the static site
* Regenerate package-lock.json by removing it and running a fresh `npm install`
Closes #118 
* Delete `node_modules`, run `npm install` followed with `npm start` in `www`
=> Fix `package-lock.json`

www/package-lock.json, www/package.json, www/src/App.tsx, www/src/routes/MobileLanding.tsx
Create mobile version of static site.
I wanted to keep this version as simple as possible to avoid further dev work on just layout / making it responsive. So this will be a temporary solution for users going to the site on mobile. I think when this is fully deployed, I'd want to essentially render a mobile-friendly version of our static site if a user opens it on their phone. This way, they can still get information about the program but they'd still need to go on their desktop to login and make use of the services. 
Wait until #68 is merged 
- Imported react-device-detect to detect if the app is open on a mobile device 
- Added MobileLanding route 
Closes #122 
To test locally (I just found this out lmao), find your IPv4 address then open your browser on your phone and enter …
=> Mobile view for static

api/package-lock.json, api/package.json, api/src/controllers/resumeReview/postResumeReview.ts
Update fluent validation library. There was a bug in the library that prevented chaining `mustAsync` method calls. I opened an [issue](https://github.com/AlexJPotter/fluentvalidation-ts/issues/18) and the maintainer fixed it :smile:.
=> Update fluent validation library

www/src/routes/Landing.test.tsx, www/src/setupTests.ts
* Individual tests no longer need to set-up enzyme per test file
* Move Enzyme configuration to `setupTests`
Closes #131 
Running `npm test` in `www` should not yield any errors
=> Move enzyme boilerplate to `setupTests.ts`

api/src/controllers/middleware.test.ts, api/src/controllers/middleware.ts, api/src/exceptions/NotAuthenticatedException.ts, api/src/exceptions/exception.test.ts
Improve authentication middleware.
- Catch error thrown by `checkJwt` when a request is not authenticated
- Add a new `NotAuthenticatedException`
N/A
Next PR will add authentication 
See unit tests
=> Improve authentication middleware

www/src/redux/substores/student/thunks/initiateResumeReview.test.tsx, www/src/redux/substores/student/thunks/initiateResumeReview.tsx, www/src/redux/thunks/checkUserRegistration.test.ts, www/src/redux/thunks/checkUserRegistration.ts, www/src/redux/thunks/registerUser.test.ts, www/src/redux/thunks/registerUser.ts, www/src/util/auth0/postWithToken.ts, www/src/util/endpoints.ts, www/src/util/scopes.ts, www/src/util/serverResponses.d.ts, www/src/util/testConstants.ts
Allows front end component to easily post the resume review data to the server as
```ts
const dispatch = useStudentDispatch();
dispatch(
initiateResumeReview({
userId: user?.sub ?? '',
tokenAcquirer: getAccessTokenSilently,
base64Contents: 'base64contentx',
}),
);
```
* Add service call in non-exported `initiateResumeReview`
* Add thunk wrapped call in default export `initiateResumeReview`
* Prefix endpoints with `get` and `post` accordingly
* Delegate try catch for `postWithToken` and `fetchWithToken` to user
* Copy scopes from server
* Replace `db.TimestampTzString` to simply `string`
* Might want to revisit to clean up the redux types
* Sadly `expect(async () => ...).toThrow(...)` [doesn't work](https://github.com/facebook/jest/issues/1700) and best syntax I could find looks like …
=> Add create resume review thunk

www/src/redux/substores/student/slices/resumeReviewSlice.ts, www/src/redux/substores/student/thunks/getMyResumeReviews.tsx, www/src/routes/student/ResumeReview.test.tsx, www/src/routes/student/ResumeReview.tsx, www/src/util/endpoints.ts, www/src/util/serverResponses.d.ts
* Fetch resume review objects when the user lands on the resume review page as a student
* Implemented getMyResumeReviews thunk
* Integrated thunk with resumeReviewSlice
* This will unblock #181 
Closes #186 
Refer to unit tests
=> Fetch resume reviews on student app

api/src/controllers/user/getRoles.test.ts, api/src/controllers/user/getRoles.ts, api/src/controllers/user/index.ts, api/src/repositories/userRolesRepository.ts, api/src/routes/userRoutes.ts, api/src/util/testConstants.ts
* Allow front end to get available roles for current user
* Create userRoleRepository
* Add new `user/:userId/roles` route
* The `user` path in the Auth0 call must not be escaped to make it work
Closes #72 
Refer to unit tests
=> Implement GET user/:userId/roles 

api/src/controllers/user/getMe.test.ts, api/src/controllers/user/getMe.ts, www/src/App.test.tsx, www/src/App.tsx, www/src/components/LoadingOverlay.tsx, www/src/redux/slices/registerUserSlice.ts, www/src/redux/slices/userSlice.ts, www/src/redux/store.ts, www/src/routes/Unauthenticated.test.tsx, www/src/routes/Unauthenticated.tsx, www/src/routes/student/Register.tsx, www/src/util/testConstants.ts
* Allow developers to register themselves without manually posting to the backend
* Prevent users from double registering by redirecting users back to the home page from the register page
* Move form state to redux
* Add submit button in register page
* Move redirect to register page to unauthenticated app
* Cleaned up tests in App.tsx
* Fix missing `.end()` call in backend that results a 200 code even when user doesn't exist
* Add loading overlays when auth0 is loading or we're fetching the backedn
* Styling will be handled in a separate PR by @AnushkaKhare-Eng 
Closes #107
Refer to unit tests
=> Integrate register button with redux

www/README.md, www/package.json
* Allows devs to fetch token with scopes without user consent (mimics how staging and prod behaves)
* Use https port to serve local front end
* Add instructions on how to add new non-localhost mapping to `/etc/hosts`
* Auth0 doesn't allow [skipping user consent for apps hosted in localhost](https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications). A dev fix for this would require us to make localhost behave as if it was hosted elsewhere
* Adding a new entry in `/etc/hosts` allows our machine to "host" on a domain other than "localhost"
* Actual non-localhost URL isn't added to prevent anyone from cloning this repository and messing up our dev environment (Auth0's original intention)
Token fetches without prior consent from …
=> Use https for local front end dev

www/src/App.test.tsx, www/src/App.tsx, www/src/components/user/EditRolesDialog.tsx, www/src/components/user/SettingsDialog.test.tsx, www/src/components/user/SettingsDialog.tsx, www/src/redux/slices/userSlice.ts, www/src/util/testConstants.ts
* Allows users to properly switch between roles by toggling the role switches in the settings popup
* Disables some of the role switches if user does not have appropriate roles
* Update dialog content
* Rename EditRolesDialog to SettingsDialog
* Does not implement the user details form (year and specialty)
Closes #174 
Closes #173 
Merge #202 locally and assign yourself `reviewer`, `interviewer` or `admin`, you should unlock the corresponding switches. As a volunteer, the `/resume-review` page should have an unstyled list of resumes available for review.
=> Integrate role switches to views

www/src/components/pdf/PDFViewer.tsx, www/src/components/pdf/ViewerSDKClient.ts, www/src/redux/substores/volunteer/slices/resumeReviewEditorSlice.ts, www/src/redux/substores/volunteer/volunteerStore.ts, www/src/routes/volunteer/ResumeReviewEditor.test.tsx, www/src/routes/volunteer/ResumeReviewEditor.tsx, www/src/routes/volunteer/thunks/getMyDocuments.test.ts, www/src/routes/volunteer/thunks/getMyDocuments.ts, www/src/util/endpoints.ts, www/src/util/serverResponses.d.ts, www/src/util/testConstants.ts
* Allow volunteers to review resumes by opening `/resume-reviews/:resumeReviewId`
* Add fetch documents thunk
* Display annotation tools in PDFViewer in resume review page for volunteers
* Add `onSave` prop to ViewerSDK to save edit file locally
* The _Complete Button_ handler will be done in a separate PR
* I need a refresher whether we should POST another document or PATCH the current one for this handler
Closes #200 
https://user-images.githubusercontent.com/43416725/130524936-0ba17077-624e-43d8-baf7-476a5afe9920.mov
(sorry for low quality, there's a 10MB file cap :') )
Depends on #204
=> Implement ReviewResumeEditor component

auth0/rules/Email domain whitelist.js, auth0/rules/domainWhitelist.js, auth0/tenant.yaml, www/src/App.tsx, www/src/providers/Auth0ProviderWithHistory.tsx
* Display error and do not proceed with log-in when user logs in using their personal (non-ualberta.ca) email
* Added rule in Auth0 that validates the email domain
* Remove unused scope field in `Auth0Provider`
* When Auth0 triggers the _UnauthorizedError_, the `isAuthenticated` flag won't be turned on so everything should stay as is (user isn't logged in even if they chose their personal email in the selection page)
* User has to clear their cookies to be able to choose a second account. We could maybe simplify this by auto clearing their cookies(?)
* TODO: Replicate auth0 changes in prod
Closes #218 
Try log-in to staging with your personal email
=> Only allow ualberta.ca emails to login to our app

www/src/components/TitledPage.tsx, www/src/routes/student/ResumeReview.tsx, www/src/routes/student/resumeReview/ResumeList.test.tsx, www/src/routes/student/resumeReview/ResumeList.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.test.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.tsx, www/src/styles/theme.ts
Display list of resume reviews that a student has and fix variable top margin on titled pages using `TitledPage` component
* Created ResumeReviewCard to display resume review objects
* Customized material UI to not use rounded corners by default
* Current resume is for resumes just submitted or still under review
* Submitted resumes is for completed/cancelled reviews
* Buttons like _View_ and _Download Resume_ aren't functional yet, they'll be followed up after I work on the POST document for a reviewer
* `cancelled` should display `<NoResumes />` (like `finished`) instead of the simple text portrayed in the screenshot below
Closes #125 
Refer to unit tests and see screenshots below
| State | Result |
| --- | --- |
| seeking_reviewer | <img width="1796" alt="seeking_reviewer" …
=> Implement ResumeList for students

www/src/redux/substores/student/slices/resumeReviewSlice.ts, www/src/redux/substores/student/thunks/cancelResumeReview.ts, www/src/routes/student/resumeReview/ResumeList.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.test.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.tsx, www/src/util/testConstants.ts
* Allow users to cancel resume review requests before they are claimed
* Add `shouldReload` field, mimicking what's happening in volunteer app
* Add cancel resume review thunk which patches the resume review as cancelled
* No tests because WE'RE RUNNING OUT OF TIME 😱
Test in staging/dev. Clicking cancel should reload the list and move it to cancelled
=> Implement cancel review

api/src/controllers/calendly/getCalendlys.ts, www/src/redux/substores/student/slices/mockInterviewSlice.ts, www/src/redux/substores/student/studentStore.ts, www/src/redux/substores/student/thunks/getCalendlys.tsx, www/src/redux/substores/volunteer/slices/mockInterviewSlice.ts, www/src/redux/substores/volunteer/thunks/getCalendlyLink.tsx, www/src/redux/substores/volunteer/thunks/setCalendlyLink.tsx, www/src/redux/substores/volunteer/volunteerStore.ts, www/src/routes/student/MockInterview.tsx, www/src/routes/volunteer/MockInterview.tsx, www/src/util/endpoints.ts, www/src/util/serverResponses.d.ts, www/src/util/testConstants.ts
Frontend code to fetch Calendly links
- 2 thunks for interviewer
- 1 thunk for student
- `manyToCamelCase` helper was modifying strings which was a problem b/c it prevented me from filtering on interviewee id. Instead of spending time investigating I just manually did the case transformation.
Still need to do auth next.
=> Frontend code to fetch Calendly links

www/src/routes/volunteer/ResumeReview.tsx, www/src/routes/volunteer/thunks/patchResumeReview.ts
* Fix scenario when volunteer completes a resume review but is still listed under their currently reviewing section
* Update the thunk to return the `Promise<void>` object
* Group the two fetches together since they're kind of bound to each other via shouldReload
* Root cause was we didn't wait for the asynchronous function to finish so before patch resume review was done, it already triggered the `.fulfilled` event
Closes #231
Completing a resume review in staging should now remove the entry in currently reviewing without a refresh
=> Fix volunteer resume list reloading too fast

www/src/components/auth/UserProfile.test.tsx, www/src/components/auth/UserProfile.tsx, www/src/components/user/SettingsDialog.tsx, www/src/redux/slices/userSlice.ts, www/src/util/testConstants.ts
What is the high-level goal of this PR? Is there any important context we should have?
- Settings dialog closes when role is changed
- User Profile dialog also closes when role is changed 
- Not 100% if we want this, I can easily rollback the commit if we want to keep the user profile dialog open when role changes
Closes #239 
https://user-images.githubusercontent.com/32345990/132966815-75850cd6-3b30-450f-89af-a92ee558827f.mov
=> Close Dialog on switching roles

www/src/components/user/SettingsDialog.tsx
Closes the User Profile dialog when the Settings dialog is closed too 
- Updated Settings.tsx to close the UserProfileDialog when settings is also closed 
- Set the `disabled` prop for the "ccid" menu item so that it's not clickable 
https://user-images.githubusercontent.com/32345990/132999336-ec89e675-b9fd-4bfc-b593-0c867bbd745e.mov
=> General UI changes to settings 

www/src/App.tsx, www/src/components/pdf/PDFViewer.tsx, www/src/routes/student/resumeReview/ResumeReviewViewer.tsx, www/src/routes/volunteer/ResumeReviewEditor.tsx, www/src/styles/index.css
* Make reviewers enjoy their resume reviewing process more :)
* Replace root container with a `flex` container (more on this later)
* Hijack the Adobe PDF's `iframe`, essentially adding `flex-grow: 1` to it so that it can fill the parent's div
* `flex-grow` allows components to fill in the remaining `flex` parent
* I replaced the `resumeReviewId` with the reviewee's name, fetched from the resume review list
* If the reviewer refreshes the editor page, they'll lose this name
* We can fix it easily by fetching for the `resumeReviews` using the same thunk but let's do that in a separate PRR
Closes #240
See in staging
https://user-images.githubusercontent.com/43416725/133196834-13c7c754-357d-4b0c-943b-8f028671f6fc.mov
=> Fix PDF components to fill in rest of screen

api/src/controllers/document/patchMyDocument.test.ts, api/src/controllers/document/patchMyDocument.ts
* Allow reviewers to review resumes other than their own
* Replace `documentRepository.get` with `documentRepository.getAssociatedToUser`
* Previously verifying user association previously used the `userId` field which only allowed reviewers to review their own resume review (returning 403)
* Using `getAssociatedToUser` verifies that the volunteer is associated to the document via the resume review object
Closes #254
1. In `dev` environment, comment [this line from `postUser.ts`](https://github.com/UAlbertaCompEClub/compe-plus/blob/97b93e916cfd8835365964edb3237a1e06dd2fec/api/src/controllers/user/postUser.ts#L24) and register your personal email.
2. Upload a resume for review using that personal email.
3. Review the resume using your ualberta email.
4. Verify that PATCH document returns …
=> Fix patch doc

www/src/redux/substores/volunteer/slices/resumeReviewSlice.ts, www/src/routes/volunteer/ResumeReview.tsx
Added refresh button so that volunteers can easily see any changes to the available resumes table 
- Created action to set `shouldReload` for resume review slice 
- Added button to resume review page 
Closes #258
https://user-images.githubusercontent.com/32345990/133369151-16314ccb-0e7b-47d6-9629-4c2c7bc66053.mov
=> Refresh Button for Resume Reviews

www/package-lock.json, www/package.json, www/src/index.tsx, www/src/redux/store.ts, www/src/util/testConstants.ts
* Allow volunteers to stay as volunteers in the event that they have to refresh a page
* Install and integrate redux-persist
* Data is stored in localStorage but the globalStore has no sensitive data other than year and program of the last registered user
* Eliminates the scenario where a student can see another student's resume when they switch back from reviewer to student in the editor
Closes #255
As a volunteer, refresh the resume review page, you should stay as a volunteer
=> Persist userRole between refreshes

api/src/controllers/resumeReview/patchAllResumeReview.test.ts, api/src/controllers/resumeReview/patchAllResumeReview.ts, api/src/controllers/resumeReview/patchMyResumeReview.test.ts, api/src/controllers/resumeReview/patchMyResumeReview.ts, api/src/repositories/resumeReviewRepository.ts, api/src/util/testConstants.ts
Prevent double claim of resume review since UI won't refresh automatically when resumes are claimed.
I want to test this on staging with someone else
=> Prevent double claim of resume review

api/src/controllers/user/getMe.ts
* Fix server side 'Cannot set client headers after sending ... to client' error because we don't `return` after `.end()`
* Add missing immediate `return` statement in `getMe.ts`
* Other files that call `.end()` already have an implicit `return`
Closes #268
* Open dev environment a user that's not registered in your local database
=> Fix 500 error for new users

api/src/controllers/middleware.test.ts, api/src/controllers/middleware.ts, api/src/exceptions/NotAuthorizedException.ts, api/src/routes/calendlyRoutes.ts, api/src/routes/documentRoutes.ts, api/src/routes/resumeReviewRoutes.ts
Prevent users from interacting with CompE+'s backend when they have not read the terms of service
Created a TOS checker middleware that's applied to all create/update endpoints
This is our last line of defence, I'll be disabling the buttons and displaying the error messages on the front end in another PR. 
Merging this PR does not pose any risk because changes are only done in backend and needs to be promoted to production in heroku before it impacts anyone.
Part of #278
Using the new schema try posting a resume for review without having agreed to the terms of service 
You'll get an infinite loading spinner at the moment but I plan to display an error message where it educates users on where they can click to read/agree the TOS
=> Prevent create/update endpoints in backend when user has not agreed to TOS

www/src/App.test.tsx, www/src/contexts/UserContext.tsx, www/src/hooks/useUserContext.tsx, www/src/index.tsx, www/src/providers/UserProvider.tsx, www/src/routes/student/MockInterview.test.tsx, www/src/routes/student/MockInterview.tsx, www/src/routes/student/resumeReview/MockInterview.test.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.test.tsx, www/src/routes/student/resumeReview/ResumeReviewCard.tsx, www/src/routes/student/resumeReview/UploadResume.test.tsx, www/src/routes/student/resumeReview/UploadResume.tsx, www/src/routes/volunteer/MockInterview.tsx, www/src/routes/volunteer/ResumeReview.test.tsx, www/src/routes/volunteer/ResumeReview.tsx, www/src/routes/volunteer/ResumeReviewEditor.tsx, www/src/routes/volunteer/ResumeReviewTable.tsx, www/src/util/testConstants.ts
Disable the following actions for users who have not agreed to our terms of service
* For students
* Requesting/cancelling resume reviews
* Getting their calendly links
* For volunteers
* Claiming/unclaiming/reviewing resumes
* Uploading a mock interview link
* Create a custom user context because the global store isn't working as expected
* TL;DR you can only have one store provider, once we go into the student/volunteer apps, we can no longer access the global store 
* Disable buttons when user hasn't agreed to our terms of service
* Hide links when user hasn't agreed to our terms of service
* Disable hover and interaction for upload resume when user hasn't agreed to our terms of service
* How to best hide the hidden link in the mock interview page?
* Best to merge #289 first so that …
=> Disable front end interactions for users that have not agreed to TOS

www/src/App.test.tsx, www/src/App.tsx, www/src/components/TermsOfServiceAlert.test.tsx, www/src/components/TermsOfServiceAlert.tsx, www/src/components/auth/UserProfile.tsx, www/src/redux/slices/userSlice.ts
Terms of service alert is currently displayed to all users (authenticated or not) because there was no check for this. We only checked if the user has agreed to terms of service and undefined is a falsy value.
Also clear persisted user information when the user is logged out (either through the Logout button or automatically due to JWT expiry)
* Add check for authentication status in terms of service alert component
* Simulate clearing the user state when the user is logged out
1. From master branch, comment out `dispatch(reset())` in UserProfile
2. Log-in to local.compe.plus
3. Log-out
4. Open resume review page and verify that you have your previous view (you can also double check your local storage and see that the current role is not "")
5. Add the `dispatch(reset())` call to App.tsx …
=> Hide terms of service alert for unauthenticated users
