UAlbertaCompEClub/compe-plus

README.md, tech-stack.md
@cyrusdiego let me know what you think about this:
- Do you disagree with any decisions I made?
- Did I forgot to call anything out?
- Anything in the open questions that you think is an obvious decision and we should mark down as decided?
Closes #2
=> Outline tech stack decisions

tech-stack.md
- Fixed hyperlinks in tech-stack.md
=> Fix Links in markdown

.github/workflows/main.yml, www/package.json
- Based CI/CD steps from api steps 
- Changed linting to be stricter (like api)
Closes #22
=> CI/CD for Frontend

api/README.md, api/db/README.md, api/db/migrations/001_initial_schema.down.sql, api/db/migrations/001_initial_schema.up.sql, tech-stack.md
- Write api README
- Write db README
- Guide for running Postgres locally
- Update tech stack guide
- Write 1st migration i.e. DB schema. Moving this to another PR to keep scope smaller
Closes #19
=> Scaffold db

README.md
Add Caleb as a teammate
N/A
N/A
N/A
N/A
=> Add Caleb as a teammate

README.md
Adding my name to the team mate list 
NA
NA
NA
Does this close any tasks?
NA
How did you test these changes? How can the reviewer test these changes?
NA
=> Anushka-Onboarding 

.github/workflows/main.yml
Added www-prod to github actions
=> CI for www-prod

.github/workflows/main.yml, www/src/App.test.tsx, www/src/components/Header.tsx, www/src/hooks/useVisibility.ts, www/src/util/test/intersectionObserverMock.ts
Targetted wrong branch in #124 (face-palm) 
Had to add a mock for IntersectionObserver. See [this](https://stackoverflow.com/questions/44249985/js-testing-code-that-uses-an-intersectionobserver) stackoverflow article
Just cherry picked commit from #124 and merging to the correct target branch
=> Add CI to www-prod

www/src/App.tsx, www/src/components/Header.tsx, www/src/routes/Landing.tsx, www/src/routes/MobileLanding.tsx
Final "catch-all" PR for small changes to the static site prior to release 
- Uncommented header sections 
- Not code related change but on MailChimp's side, on signup to the mailing list an automated email will be sent to the email confirming they joined the mailing list. 
List any relevant work that still needs to be done. Open and link to issues for them if applicable.
Does this close any tasks?
`cd www && npm run start`
=> `www-prod` release 

api/.env.sample, api/src/controllers/middleware.test.ts, api/src/controllers/middleware.ts, api/src/server.ts, api/src/util/config.ts
* Specify allowed origins header
* Configure `cors` as mentioned in [Configuring CORS w/ Dynamic Origin](https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin)
* Do we want to fail a request if it doesn't have the origin tag? Cors wasn't designed for security so I personally think it should not throw an error
* This doesn't support preview builds yet because they have funky origin names and we might need regex to handle that
Closes #65
Refer to unit tests
=> Configure cors

api/src/controllers/resumeReview/index.ts, api/src/controllers/resumeReview/patchAllResumeReview.test.ts, api/src/controllers/resumeReview/patchAllResumeReview.ts, api/src/controllers/resumeReview/patchMyResumeReview.test.ts, api/src/controllers/resumeReview/patchMyResumeReview.ts, api/src/repositories/resumeReviewRepository.ts, api/src/routes/resumeReviewRoutes.ts
Implement patch resume review endpoints
Closes #77
=> Implement patch resume review endpoints

www/public/index.html, www/public/manifest.json
* Update web previews on apps like discord
* Updated the description in `index.html`
* Updated the manifest for PWA
Closes #183
Refer to preview deployment
=> Update web metadata

api/package-lock.json, api/package.json, api/src/controllers/document/patchAllDocument.ts, api/src/controllers/document/patchMyDocument.ts, api/src/controllers/document/postDocument.test.ts, api/src/controllers/document/postDocument.ts, api/src/controllers/resumeReview/getAllResumeReviews.test.ts, api/src/controllers/resumeReview/getAllResumeReviews.ts, api/src/controllers/resumeReview/getMyResumeReviews.test.ts, api/src/controllers/resumeReview/getMyResumeReviews.ts, api/src/controllers/resumeReview/postResumeReview.test.ts, api/src/controllers/resumeReview/postResumeReview.ts, api/src/controllers/user/getMe.test.ts, api/src/controllers/user/getMe.ts, api/src/controllers/user/postUser.ts, api/src/controllers/validation.ts, api/src/util/helper.ts, www/src/redux/thunks/registerUser.test.ts, www/src/redux/thunks/registerUser.ts, www/src/util/serverResponses.d.ts, www/src/util/testConstants.ts
Use some fancy types and converters so that we can use camel case in both input and output of API.
Closes #164
=> Consistently use camel case throughout api

api/.env.sample, api/src/util/config.ts, api/src/util/pool.ts
Turns out staging and prod could never actually connect to the database. LMAO. Here is a hotfix.
=> Hotfix for postgres connection

api/db/migrations/003_add_calendly_resource.down.sql, api/db/migrations/003_add_calendly_resource.up.sql, api/src/zapatos/schema.d.ts
- New db migration to add calendly resource
- Zapatos schema updated
I need to run these migrations on staging and prod when this merges
=> Write SQL migrations for new Calendly resource

api/src/controllers/calendly/getCalendlys.test.ts, api/src/controllers/calendly/getCalendlys.ts, api/src/controllers/calendly/index.ts, api/src/controllers/calendly/patchCalendly.test.ts, api/src/controllers/calendly/patchCalendly.ts, api/src/controllers/calendly/postCalendly.test.ts, api/src/controllers/calendly/postCalendly.ts, api/src/controllers/validation.test.ts, api/src/controllers/validation.ts, api/src/repositories/calendlyRepository.ts, api/src/routes/calendlyRoutes.ts, api/src/server.ts
Endpoints to interact with calendly resource. Note that to speed up the implementation I didn't differentiate between my/any endpoints. Nothing particularly confidential about it anyways.
- POST endpoint
- GET endpoint
- PATCH endpoint
- Next PR is going to add authorization.
- I skipped testing for speed of implementation
- Dependent on schema migration PR #220
=> Write calendly endpoints

www/src/routes/Admin.tsx, www/src/routes/Community.tsx, www/src/routes/Student.tsx, www/src/routes/Unauthenticated.tsx, www/src/routes/Volunteer.tsx
Just added link to a Github repo containing README to hold CompE related resources 
Moved `<Community />` to same level as role specific apps 
If you have any resources to add send them my way plzzzzz
One thing that bothers me but it's pretty minor is the way we organized the static pages, the title "Community" is pushed up when I added the additional line so it's not consistent with the other pages :(
=> Community Page 

api/src/routes/calendlyRoutes.ts, api/src/types/scopes.ts, auth0/tenant.yaml, www/src/redux/substores/student/slices/mockInterviewSlice.ts, www/src/redux/substores/student/thunks/getCalendlys.tsx, www/src/redux/substores/volunteer/slices/mockInterviewSlice.ts, www/src/redux/substores/volunteer/thunks/getCalendlyLink.tsx, www/src/redux/substores/volunteer/thunks/setCalendlyLink.tsx, www/src/util/scopes.ts
Authorization for calendly resources
- Auth for backend endpoints
- Auth for frontend calls
- Add permissions to Auth0
Will need to apply to staging and prod
=> Authorization for calendly resources

www/src/components/Header.tsx, www/src/routes/unauthenticated/Landing.tsx, www/src/routes/unauthenticated/MobileLanding.tsx, www/src/routes/unauthenticated/__snapshots__/Landing.test.tsx.snap
What is the high-level goal of this PR? Is there any important context we should have?
- Removed mailing list 
- Updated Footer 
- Updated mobile (hide login, edit text, remove footer, remove mailing list)
=> Landing page update 

www/src/routes/student/Register.tsx
What is the high-level goal of this PR? Is there any important context we should have?
- Register.tsx
Closes #195
=> Registration Redirect

www/src/routes/unauthenticated/Landing.tsx
Fix typo in Landing Page 
@armiantos @calebschoepp if you guys approve this sometime tonight or during the day feel free to merge it and deploy to prod. With my schedule tmrw I won't be able to attend to this till 4pm or after 8pm :/
=> Landing Page Typo 

www/package-lock.json, www/package.json, www/src/routes/student/resumeReview/UploadResume.tsx
* Style upload resume button to look more like the mockups
* Install [react-dropzone](https://react-dropzone.js.org/)
* Create custom _Browse computer_ button (none of the material styles seem to fit what we want, i.e. color, typography, and border-radius)
* Most of the functionality has been taken care of by `react-dropzone` we just need a root div and a dummy input
Closes #243 
https://user-images.githubusercontent.com/43416725/133002150-479c810f-f487-40de-9d74-a561c9cf3f66.mov
=> Style upload button

www/src/redux/substores/student/slices/resumeReviewSlice.ts, www/src/routes/student/resumeReview/ResumeList.tsx
Refresh button to refresh current and compelted resume reviews for students
=> refresh button for student's resumes

www/src/routes/student/ResumeReview.tsx
Give context of resume reviews to students
=> small update to resume page 

www/src/routes/volunteer/ResumeReviewEditor.test.tsx, www/src/routes/volunteer/ResumeReviewEditor.tsx
* Refetch for reviewing resumes when performing a refresh in the editor vview
* Fetch for reviewing resumes when it hasn't been fetched (the case for refresh)
* I'm re-using the `getReviewingResumes` instead of creating a new `getSpecificResume` to minimize risk and reviewing resumes is capped at 3 so the difference in response time isn't too bad
Closes #251 
Refer to tests and demo below
https://user-images.githubusercontent.com/43416725/133825369-4403787d-c7a2-4eb5-a160-97eead6ea00c.mov
=> Fix missing reviewee name on refresh
